#!/bin/sh
# Recipe for the first-party zsh package (T020): populate dist/<os>-<arch>/ with
# static, hermetic, relocatable zsh builds for the delivery matrix (§FR-008,
# Принцип II). Uses romkatv/zsh-bin releases — statically linked against musl on
# Linux (works on glibc and musl hosts alike) and relocatable by design.
#
# Usage: ./fetch.sh [os-arch ...]      (default: the full matrix below)
#
# Each dist/<os>-<arch>/ is a self-contained tree (bin/zsh + share/ + lib/); xxh
# packs the tree matching the detected host platform as one content-addressed
# Shell component and delivers it to ~/.xxh/cache/<hash>/ on the host.

set -eu

ZSH_BIN_VERSION="${ZSH_BIN_VERSION:-v6.1.1}"
ZSH_VERSION="${ZSH_VERSION:-5.8}"
BASE_URL="https://github.com/romkatv/zsh-bin/releases/download/${ZSH_BIN_VERSION}"

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

matrix="${*:-linux-x86_64 linux-aarch64 linux-armv7l darwin-x86_64 darwin-arm64}"

# zsh-bin bakes /usr/local/share/zsh into fpath; on the host the tree lives in
# ~/.xxh/cache/<hash>/ instead. zsh imports FPATH from the environment, so this
# env.sh (sourced by xxh with XXH_COMPONENT_DIR set) points it at the delivered
# functions — completion (compinit) works without any relocation step.
write_env_sh() {
    cat > "$1/env.sh" <<'EOF'
# generated by fetch.sh — point zsh at the delivered completion functions
for _d in "$XXH_COMPONENT_DIR"/share/zsh/*/functions; do
    [ -d "$_d" ] && FPATH="$_d${FPATH:+:$FPATH}"
done
export FPATH
unset _d
EOF
}

for target in $matrix; do
    os=${target%%-*}
    arch=${target#*-}
    name="zsh-${ZSH_VERSION}-${os}-${arch}"
    dest="$here/dist/$target"
    if [ -x "$dest/bin/zsh" ]; then
        write_env_sh "$dest"
        echo "== $target: already present, refreshed env.sh"
        continue
    fi
    echo "== $target: fetching $name.tar.gz"
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT INT TERM
    curl -fsSL "$BASE_URL/$name.tar.gz" -o "$tmp/$name.tar.gz"
    # The tarball has no top-level directory: bin/ + share/ + man/ at the root.
    # zsh-bin trees are relocatable: ship them together as one unit.
    mkdir -p "$dest"
    tar -xzf "$tmp/$name.tar.gz" -C "$dest"
    write_env_sh "$dest"
    rm -rf "$tmp"
    trap - EXIT INT TERM
    echo "== $target: done -> $dest/bin/zsh"
done
